export { Slider } from './slider'
export { PaymentsInformation } from './payment'
export { ShippingInfo } from './shipping'
export { Buttons } from './buttons-actions'
export { Accordion } from './accordion'
export { QuantityArea } from './quantity-area'
